function(exsim_enable_sanitizer kind)
    if(kind STREQUAL "")
        return()
    elseif(kind STREQUAL "address")
        set(flags -fsanitize=address,undefined -fno-sanitize-recover=all)
    elseif(kind STREQUAL "thread")
        set(flags -fsanitize=thread)
    else()
        message(FATAL_ERROR "Unknown EXSIM_SANITIZER '${kind}' (expected '', 'address' or 'thread')")
    endif()

    add_compile_options(${flags} -fno-omit-frame-pointer)
    add_link_options(${flags})
endfunction()
